Ethar
Etharabdou10/laravel-R6 pull request #1
Opened 2024-07-25 23:41 UTC by Etharabdou10

task6

2024-07-28 08:35 UTC, Nora-Lootfy approved these changes
Good job ya Ethar, you have nailed it

2024-07-31 08:38 UTC, Nora-Lootfy commented on app/Http/Controllers/ClassController.php
> +            'capacity'=>'required|string|max:50',
capacity is not a string it is integer number `number of students class can take`

2024-07-31 08:40 UTC, Nora-Lootfy approved these changes
Remember ya Ethar to close pull request and merge with main `after i review your code` , so your code appear into main branch

2024-08-07 00:44 UTC, Nora-Lootfy commented on resources/views/products.blade.php
> +                                    <img src="{{asset('assets/images/' .$product->image ) }}" class="img-fluid product-image" alt="">
i think you have mistaken here, i couldn't find your foreach

DM me if you fix it

2024-08-07 00:45 UTC, Nora-Lootfy requested changes
a little bug in your view file, try to fix it

2024-08-11 06:54 UTC, Nora-Lootfy commented on app/Http/Controllers/ProductsController.php
> +    public function about()
personally, i don't like to put the public pages in the crud controller and i will tell you why

if you open the about page, you will find a section called meet our team, is this section belongs to products?

The way i prefer to work with is that and a send it as text file in the group called organizeFiles

if your website has two sections
Public pages ==> like the template of Fashion
Admin pages ==> like the crud of cars, products ...etc

for controllers
- i separate my controllers in directory called `Admin` for crud controllers or any pages for admin only
- for the public pages, it depends on the pages if there are a lot of pages i make more than one controller each one serve part of public pages & if the number of pages is small, i make one controller e.g. `PublicController` and make function for each page 
      - for example
 ```php
class PublicController {
    public function index() {
        // for index page
    }
    public function about() {
        // for about page
     }
    ...
}
```

2024-08-11 06:54 UTC, Nora-Lootfy commented on app/Http/Controllers/ProductsController.php
> +          $data['image']=$this->uploadFile($request->image,'assets/images');
you upload files to `assets/images`

2024-08-11 06:55 UTC, Nora-Lootfy commented on database/factories/ProductsFactory.php
> +             'image'=>basename(fake()->image(public_path('assets/images/products'))),
so why when you generate fake data upload to different directory, doesn't make sense

2024-08-11 06:57 UTC, Nora-Lootfy commented on resources/views/edit_product.blade.php
> +                <img src="{{asset('assets/images/' .$product->image ) }}" alt="{{$product['title']}}"   style="max-width:150px"/>
what if you are trying to edit fake generated data you will not see an image here as it is in a different directory

2024-08-11 07:00 UTC, Nora-Lootfy requested changes
could you please close the pull request after modifying the images path, there is a green button called `merge pull request`

you must open pull request each task, it is hard to review your code

2024-08-13 23:52 UTC, Etharabdou10 reviewed
@Nora-Lootfy

2024-08-14 00:02 UTC, Nora-Lootfy commented
don't reopen it ya @Etharabdou10, merge the pull request then open a new pull request each time

2024-08-14 00:03 UTC, Nora-Lootfy commented on app/Http/Controllers/CarController.php
> +           'category_id' => 'required|exists:categories,id',
nice one

2024-08-14 00:04 UTC, Nora-Lootfy commented on resources/views/edit_car.blade.php
> +        <option value="{{ $category->id }}" @selected(old('category_id') == $category->id || (isset($car->category_id) && $car->category_id == $category->id))>{{ $category->category_name }}</option>
try this
```php
@selected(old('category_id', $car->category_id) == $category->id)
```

2024-08-14 00:04 UTC, Nora-Lootfy commented on resources/views/edit_car.blade.php
> +                @error('category_name')
category_id not category_name

2024-08-14 00:04 UTC, Nora-Lootfy commented on resources/views/add_car.blade.php
> +                <option value="{{$category->id}}">{{$category->category_name}}</option>
try this
```php
@selected(old('category_id') == $category->id)
```

2024-08-14 00:05 UTC, Nora-Lootfy approved these changes
Merge the pull request😭

2024-08-14 14:50 UTC, merged